server:
  port: 8081

camunda:
  client:
    mode: self-managed
    zeebe:
      enabled: true
      grpc-address: http://localhost:26500
      rest-address: http://localhost:8080

api:
  base-path:
    prefix: "/"
