spring.application.name: @project.artifactId@
spring.main.banner-mode: off
server.port: 8080

logging.structured.format.console: ecs

camunda:
  client:
    mode: self-managed
    zeebe:
      enabled: true
      grpc-address: http://localhost:26500
      rest-address: http://localhost:8080

api:
  base-path:
    prefix: "/"
